# Generated by Django 4.1 on 2023-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
