name: My app CI/CD

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
      - name: get static files
        id: changed-static-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/static/**
      - name: Run step only when any of the above static files changed.
        if: steps.changed-static-files.outputs.any_changed == 'true'
      - run: |
          echo "static files"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done