name: My app CI/CD

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest

  development:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    needs: [tests]
    if:
      contains('refs/heads/develop', github.ref )
    steps:
      - name: merged request
        run: |
          echo PR ${{github.refs}} ${{ github.ref_name }} ${GITHUB_REF##*/}
      - name: Verify static files
        id: verify-static-files
        with:
          files: |
             **/static/**

      - name: Run step only when any of the above static files change.
        if: steps.verify-static-files.outputs.all_modified_files == 'true'
        run: |
          echo "Changed static files" 

  production:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    needs: [tests]
    if:
      contains('refs/heads/main', github.ref )
    steps:
      - uses: actions/checkout@v3
      - name: merged request
        run: |
          echo PR ${{github.refs}} ${{ github.ref_name }} ${GITHUB_REF##*/}
      - name: Verify static files
        id: verify-static-files
        with:
          files: |
            **/static/**

      - name: Run step only when any of the above static files change.
        if: steps.verify-static-files.outputs.all_modified_files == 'true'
        run: |
          echo "Changed static files"
