# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Close Pull Request

# only trigger on pull request closed events
on:
  push:
  pull_request:
    types: [ closed ]

jobs:
  tests:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Test with pytest
        run: |
          pytest

  deploy in dev:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true && contains('refs/heads/develop', github.refs)
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged

  deploy in prod:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true && contains('refs/heads/main', github.refs)
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged