# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Humdrum CI/CD

on:
  push:
    branches:
  pull_request:
    types: [ closed ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3

        if: github.refs == 'refs/heads/feature/*' && github.event.pull_request.merged == true
      - name: Display text
        run: echo 'hello' ${{ github.refs }}
        if: github.event.pull_request.merged == true
      - name: Display text
        run: echo 'merged'
        if: github.event.pull_request.merged == false
      - name: Display text
        run: echo 'opened'
        if: github.refs == 'refs/heads/feature/*'
      - name: Display text
        run: echo 'branches' ${{ github.refs }}
