# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Humdrum CI/CD

on:
  push:
    branches:
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3

      - name: Display text
        run: |
          if ((github.event_name == 'pull_request') and (github.event.action == 'closed') and (github.event.pull_request.merged == true)):
          then print("pull request merged");
          if not (github.event_name == 'pull_request' and github.event.action == 'closed' and github.event.pull_request.merged == true)):
          then print("hello user");
        shell: python