name: My app

on:
  push:
    branches:
  pull_request:
    branches:
      - 'develop'
      - 'feature/*'
    types:
      [created, closed ]

jobs:
  tests:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest

  development:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
      - name: merged request
      - run: |
          echo PR ${{github.refs}} ${{ github.ref_name }} ${GITHUB_REF##*/}
