name: My app CI/CD

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: python
      - name: Test with pytest
        run: |
          pytest

  development:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    needs: [ tests ]
    if:
      contains('refs/heads/develop', github.ref )
    steps:
      - uses: actions/checkout@v3
      - name: verify static files
        id: changed-static-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/static/**
      - name: Run step only when any of the above static files changed.
        if: steps.changed-static-files.outputs.any_modified == 'true'
        run: |
          print("static files changed")
        shell: python
      - name: verify migration files
        id: changed-migration-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/000**.py
      - name: Run step only when any of the above migration files changed.
        if: steps.changed-migration-files.outputs.any_modified == 'true'
        run: |
           print("migration files changed")
        shell: python

  production:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    needs: [ tests ]
    if:
      contains('refs/heads/main', github.ref )
    steps:
      - uses: actions/checkout@v3
      - name: verify static files
        id: changed-static-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/static/**
      - name: Run step only when any of the above static files changed.
        if: steps.changed-static-files.outputs.any_modified == 'true'
        run: |
          print("static files changed")
        shell: python
      - name: verify migration files
        id: changed-migration-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **/000**.py
      - name: Run step only when any of the above migration files changed.
        if: steps.changed-migration-files.outputs.any_modified == 'true'
        run: |
          print("migration files changed")
        shell: python